spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
app.auth.private-key=${JWT_PRIVATE_KEY}
app.auth.public-key=${JWT_PUBLIC_KEY}
app.auth.secure-cookies=true
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
app.mail.mode=${MAIL_MODE:graph}
server.forward-headers-strategy=none
